### ISSUE TITLE
detail pipeline CSC API doc

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver_pipelines#20]
Detalhar documentação técnica dos pipelines com input, config params, output, alguma dica ou exemplo de uso? É nesse repo que fica isso? 

O que eu encontrei: 
https://linea-it.github.io/pzserver/autoapi/pzserver/index.html#pzserver.Pipeline

**Comment by crisingulani** [comment]
Aqui tem informações de como iniciar um processo (combine_specz_catalogs e make_training_set):
https://linea-it.github.io/pzserver/autoapi/pzserver/core/index.html

Aqui tem informações sobre as classes de processos (TSMProcess e CSCProcess): 
https://linea-it.github.io/pzserver/autoapi/pzserver/process/index.html


Como submeter um Combine Specz Catalog:
```
>>> from pzserver import PzServer
>>> pz = PzServer(token=<your token>, host="pz-dev")
>>> csc = pz.combine_specz_catalogs("Test 001")
>>> csc.append_catalog(1)
>>> csc.append_catalog(2)
>>> csc.summary()
------------------------------
Combine Specz Catalogs: Test 001
Configuration: {'debug': True}
Input catalogs: [{'name': 'spec001', 'internal_name': '1_spec001', 'id': 1}, {'name': 'spec002', 'internal_name': '2_spec002', 'id': 2}]
Status: The process has not been started
------------------------------
>>> csc.run()
{'output': {'id': 6, 'display_name': 'Test 001', 'internal_name': '6_test_001'}, 'id': 1, 'status': 'Pending'}
>>>
```
